version: '3'

services:
  db:
    image: postgres:latest
    container_name: gerencia-sessao-votacao-db-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gerencia-sessao-votacao-db-2
    ports:
      - "5432:5432"
    networks:
      - postgres_network

networks:
  postgres_network: