CREATE TABLE PAUTA
(
    ID           SERIAL PRIMARY KEY,
    TITULO       VARCHAR(255) NOT NULL,
    DESCRICAO    VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE SESSAO_VOTACAO
(
    ID              SERIAL PRIMARY KEY,
    ID_PAUTA        INT NOT NULL,
    TITULO          VARCHAR(255) NOT NULL,
    DATA_HORA_ABERTURA   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_HORA_FECHAMENTO   TIMESTAMP,
    FOREIGN KEY (ID_PAUTA) REFERENCES PAUTA (ID)
);
CREATE TABLE ASSOCIADO
(
    ID   SERIAL PRIMARY KEY,
    NOME VARCHAR(255)       NOT NULL,
    CPF  VARCHAR(14) UNIQUE NOT NULL
);
CREATE TABLE VOTO
(
    ID           SERIAL PRIMARY KEY,
    ID_ASSOCIADO INT NOT NULL,
    ID_PAUTA     INT NOT NULL,
    VOTO         VARCHAR(3) NOT NULL,
    DATA_VOTO    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ASSOCIADO) REFERENCES ASSOCIADO (ID),
    FOREIGN KEY (ID_PAUTA) REFERENCES PAUTA (ID)
);
